name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o .NET Core 8
      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Configurar o MySQL para testes
      - name: Start MySQL Service
        run: |
          choco install mysql --params "/port:3306 /password:testpassword"
          mysql --version

      # Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # Compilar o projeto
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Executar testes
      - name: Run tests
        run: dotnet test --no-build --configuration Release

        # Checar formatação
      - name: Check code format
        run: dotnet format --check
